create extension if not exists vector;
create extension if not exists pgcrypto;

create table if not exists interview_sessions (
  id bigint generated by default as identity primary key,
  role text not null,
  candidate_name text,
  resume_object_path text,
  report_object_path text,
  extracted_profile jsonb not null default '{}'::jsonb,
  summary text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists interview_turns (
  id bigint generated by default as identity primary key,
  session_id bigint not null references interview_sessions(id) on delete cascade,
  question text not null,
  answer text,
  retrieved_context jsonb not null default '[]'::jsonb,
  evaluation jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists kb_chunks (
  id uuid primary key default gen_random_uuid(),
  role text not null,
  source text not null,
  storage_path text not null,
  chunk_index integer not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1536) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (role, source, chunk_index)
);

create index if not exists kb_chunks_role_idx on kb_chunks(role);
create index if not exists kb_chunks_embedding_idx on kb_chunks using hnsw (embedding vector_cosine_ops);

create or replace function match_kb_chunks(
  filter_role text,
  query_embedding vector(1536),
  match_count integer default 5
)
returns table (
  id uuid,
  role text,
  source text,
  chunk_index integer,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
as $$
  select
    kb_chunks.id,
    kb_chunks.role,
    kb_chunks.source,
    kb_chunks.chunk_index,
    kb_chunks.content,
    kb_chunks.metadata,
    1 - (kb_chunks.embedding <=> query_embedding) as similarity
  from kb_chunks
  where kb_chunks.role = filter_role
  order by kb_chunks.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;
